name: Build and deploy SHOPPUS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Deploy dist to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: shoppus-web
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2DFEA089BE82412192D13664B67D11F1 }}
          package: dist
